sudo: false
language: node_js
node_js:
- '5.1'
env:
  global:
  # Please get your own free key if you want to test yourself
  - BROWSERSTACK_USERNAME: << USERNAME GOES HERE >>
  - BROWSERSTACK_ACCESS_KEY: << ACCESS KEY GOES HERE >>
  - SAUCE_USERNAME: << USERNAME GOES HERE >>
  - SAUCE_ACCESS_KEY: << ACCESS KEY GOES HERE >>
cache:
  directories:
  - node_modules
install:
- "travis_retry npm install grunt-cli $(node -e \"var deps = require('./package.json').peerDependencies; for(var name in deps) process.stdout.write(name + '@' + deps[name] + ' ');\")"
- travis_retry npm install
script:
- grunt
- grunt intern:node --combined
- grunt intern:saucelabs --combined
- grunt remapIstanbul:ci
- grunt uploadCoverage
