sudo: false
language: node_js
node_js:
- '6'
env:
  global:
  # Please get your own free key if you want to test yourself
  - BROWSERSTACK_USERNAME: << USERNAME GOES HERE >>
  - BROWSERSTACK_ACCESS_KEY: << ACCESS KEY GOES HERE >>
  - SAUCE_USERNAME: << USERNAME GOES HERE >>
  - SAUCE_ACCESS_KEY: << ACCESS KEY GOES HERE >>
cache:
  directories:
  - node_modules
install:
- travis_retry npm install grunt-cli
- travis_retry npm install
script:
- grunt
- grunt intern:node --combined
- grunt intern:saucelabs --combined
- grunt remapIstanbul:ci
- grunt uploadCoverage
notifications:
  slack:
    secure: gX2fGk/195mWBsjdr9I7A5pUXhfjs/MDXgM5YT6PCikbpm0sLJiVSq9e8bQjugB+pddGeRxvhr01s0Yaz8SBojHWE8TDHUOcj8zklo/baAo/bBbLrGfUZ4kEHyN56oDN9pNGkcsYcWINKNRVKzraawTlGhE/lgV7LhjDdFuTLl+qFqnc+LkArtRvvIuvwB2dryD/Ehf6g3eIyr4EXR+/7tUhpayAMeN2CG2Qzo4H6tkYypxRfFmfcOVR1C8ox3QOgJOwLVSYGXirZKylzVoH3TS4bR0zCvB/Y4yP0XWseY7VsRLS1KDx+gqtM2om/M1GkMmnqLOmHY9pilEoBCzskm2wQ74GhyJ8g09fySw1gAgbUvMFdVNiUkk96u0Ufci0Tz3ZeCxw25efekDXbF7kU0AM+S35d8H7t3inGgrr4dSNglqP/zSOldVYvJ4rKuMEehm04iwSvQ7fSjOuhTKftLeYtWYCKpNAaZa3GAZJOqh/UedzNmRVlMNd1eTCuQk2uhvuZg7h6BkS84cyZAFIQS1Y7u0QvO0SUnGhDY7GDYeKCV1ZXvrk/jdiI+4za52f/zNtrX8WTnNzbvtdbTLyGvl8keA0vwoYwCRcgxKlTbZKJEax//MsatBe3Y3ThMCIRUYysGlzXCyj8OUMiDgX5Wfw4/z/P9xayCQYWgZGPXA=
    on_success: change
